# Generated by Django 5.1.1 on 2024-10-07 09:07

from django.db import migrations, models
import uuid

def generate_unique_ids(apps, schema_editor):
    Bill = apps.get_model('bills', 'Bill')
    bills_without_uuid = Bill.objects.filter(unique_id__isnull=True)
    for bill in bills_without_uuid:
        bill.unique_id = uuid.uuid4()
        bill.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_unique_id'),
    ]

    operations = [
        migrations.RunPython(generate_unique_ids),
    ]