# Generated by Django 5.1.1 on 2024-10-07 09:08

import uuid
from django.db import migrations, models

def generate_unique_id(apps, schema_editor):
    Bill = apps.get_model('bills', 'Bill')
    for bill in Bill.objects.all():
        bill.unique_id = uuid.uuid4()
        bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_populate_unique_id'),
    ]

    operations = [
        migrations.RunPython(generate_unique_id),
        migrations.AlterField(
            model_name='bill',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
